
MTK_PM_BUILD_FOLDER=$(srctree)/drivers/misc/mediatek/performance

subdir-ccflags-y += -I$(MTK_PM_BUILD_FOLDER)/include/

obj-$(CONFIG_MTK_LOAD_TRACKER) += load_track/
obj-$(CONFIG_MTK_LOAD_TRACKER) += uload_ind/
