# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_OPLUS_SHRINK_LRUVECD_OPT)	+= kshrink_lruvecd.o
obj-$(CONFIG_OPLUS_SHRINK_SLABD_OPT)	+= kshrink_slabd.o
obj-$(CONFIG_OPLUS_PCPAGES_OPT)	+= pcppages_opt.o
obj-$(CONFIG_OPLUS_MAPPED_PROTECT_OPT)	+= mapped_protect.o
obj-$(CONFIG_OPLUS_KSWAPD_ALLOC_ADJUST_OPT)	+= kswapd_opt.o